# Generated by Django 4.2.4 on 2023-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shoppingcart',
            field=models.JSONField(null=True),
        ),
    ]
