# Generated by Django 4.2.4 on 2023-09-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cart_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
