# Generated by Django 4.2.4 on 2023-09-19 16:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/user/defaultProfile.jpg', null=True, upload_to=users.models.custom_upload_to),
        ),
    ]
