# Generated by Django 4.2.4 on 2023-09-18 01:48

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('consumer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('assessment', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('comentary', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=orders.models.custom_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.IntegerField()),
                ('consumer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('zip_code_fate', models.IntegerField(default=0)),
                ('price_fate', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('price_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('quantity_buy', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('concluded', models.BooleanField(default=False)),
                ('posted', models.BooleanField(default=False)),
                ('tracking_code', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=orders.models.custom_upload_to)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.feedback')),
            ],
        ),
    ]
