# Generated by Django 4.2.4 on 2023-08-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consumer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.IntegerField(),
        ),
    ]
