# Generated by Django 4.2.4 on 2023-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_at_order_deadline_order_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.TextField(default=''),
        ),
    ]
