# Generated by Django 4.2.4 on 2023-09-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_feedback_consumer_id_alter_feedback_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='assessment',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
