# Generated by Django 4.2.4 on 2023-09-17 00:18

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name_product', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('assessment', models.IntegerField(default=0)),
                ('specifications', models.TextField(default='')),
                ('zip_code_origin', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=products.models.custom_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ProImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.custom_upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products')),
            ],
        ),
    ]
