# Generated by Django 4.2.4 on 2023-08-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_assessment_products_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='options',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
