# Generated by Django 4.2.4 on 2023-08-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_zip_code_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
