# Generated by Django 4.2.4 on 2023-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
