# Generated by Django 4.2.4 on 2023-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_height_products_length_products_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
