# Generated by Django 4.2.4 on 2023-09-07 15:10

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=products.models.custom_upload_to),
        ),
    ]
