# Generated by Django 4.2.4 on 2023-09-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_image_remove_products_image_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='images',
        ),
    ]
