# Generated by Django 4.2.4 on 2023-09-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_image_products_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
    ]
