# Generated by Django 4.2.4 on 2023-09-09 20:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_products_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=products.models.custom_upload_to),
        ),
    ]
